# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: RLQ
name: RLQ
home_title: RLQ
home_sub_title: 人啊，你当自助！
keyword: "ren, android, 数据结构, 算法, rlq, Linux"
qq:
email: rlqjue@gmail.com
location: Beijing, China
description: > # this means to ignore newlines until "baseurl:"
  你当自助！
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ren.yyland.com" # the base hostname & protocol for your site
github_username:   rlq
github_url: https://github.com/rlq
facebook_url: https://www.facebook.com/lian.jue.92
twitter_url:
weibo_url: http://weibo.com/u/2682057371
linkedin_url: https://www.linkedin.com/in/%E5%88%A9%E7%90%B4-%E4%BB%BB-36b5a4120?trk=hp-identity-name
google_plus_url:

# Disque
disque: rlq.disqus.com

gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - jekyll-github-metadata
  - kramdown

markdown: kramdown
kramdown:
  input:  GFM
  syntax_highlighter_opts:
    disable: true

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: 首页

  -
    href: /blog
    label: 时光机

  -
    href: /about
    label: 关于

post_category_name: 博文分类
post_nav_name: 文内导航
links_name: 友情链接

links:
  -
    href: http://blog.yyland.com
    label: YangYong

  -
    href: http://imrui.net
    label: DongRui

# 多说评论
duoshuo:
  enable: true
  short_name: rlqyyland

# Google Analytics
google_tracking_id: 'UA-80478180-1'

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# https://www.google.com/cse/
google_case:
  enable: ture
  cx: 000063965395341567097:bmbju2qjbwy

# http://zn.baidu.com/
baidu_search:
  enable: false
  id: 1132595382140778164
  site: http://zhannei.baidu.com/cse/search

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, C, Android, Shell, Awk, Sed]
skill_op_keywords: [Linux, Svn, Git]
skill_web_keywords: [Flask, Boostrap, HTML, CSS, JS, JQuery]
