# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: YYland
name: YYland
home_title: 歪歪大陆
home_sub_title: 我随便写写,你随便看看.
keyword: "jason, yong, linux, op, sa, 运维"
qq: 
email: jasonyy77@163.com
location: Beijing, China
description: > # this means to ignore newlines until "baseurl:"
  我随便写写,你随便看看.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.yyland.com" # the base hostname & protocol for your site
github_username:  jasonyy77
github_url: https://github.com/jasonyy77
facebook_url: https://www.facebook.com/jasonyy77
twitter_url: https://twitter.com/jasonyy77
weibo_url: http://weibo.com/jasonyy77
linkedin_url: 
google_plus_url: https://plus.google.com/u/0/112362051377731857526/posts

# Disque
disque: yyland.disqus.com

gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - jekyll-github-metadata

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: 首页

  -
    href: /blog
    label: 时光机

#  -
#    href: /bookmark
#    label: 书签
#
  -
    href: /about
    label: 关于

post_category_name: 博文分类
post_nav_name: 文内导航
links_name: 友情链接

links:
  -
    href: http://coolshell.cn/
    label: 酷壳

  -
    href: http://tool.oschina.net/
    label: 在线工具

  -
    href: http://chenlinux.com/
    label: 三斗室

# Google Analytics
google_tracking_id: 'UA-80358538-1'

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# https://www.google.com/cse/
google_case:
  enable: ture
  cx: 000063965395341567097:bmbju2qjbwy

# http://zn.baidu.com/
baidu_search:
  enable: false
  id: 1132595382140778164
  site: http://zhannei.baidu.com/cse/search

# For about.html. Fell free to create your own!
skill_software_keywords: [Java, Python, PHP, Perl, C, lua, Android, Shell, Awk, Sed]
skill_op_keywords: [Linux, MySQL, WebServer, KVM, Docker, Network, NoSQL, Log, Svn, Git]
skill_web_keywords: [Tornado, Flask, Django, AngularJS, Boostrap, HTML, CSS, JS, JQuery, Ajax]
